### ISSUE TITLE
Mac User Question

### ISSUE THREAD

**Issue by taylorzhancher** [trading-peter/ftx-auto-lend#2]
Hello trading-peter, thanks so much for building this tool!

I'm wondering how to achieve this as a Mac user? I've git cloned, `cd`ed into the file, and typed the command but got `zsh: command not found: ftx-auto-lend-win.exe` 

Also, 
1. I've observed that FTX updates the received interest at 15 minutes after the hour starts, and only then it is possible to lend out more money. Is it possible to update by then instead of 5 minutes after the hour?
2. if I don't have other trading activities in my account, is possible to just use my main account? Because it seems that unlocking funds takes up to 6 hour. What should I do with the parameter then?

**Comment by trading-peter** [comment]
You need to use the mac version and replace the filename in the command to `ftx-auto-lend-mac`.

1: No, currently not possible
2: You should be fine if you simply omit the subaccount parameter.

**Comment by trading-peter** [comment]
Also use the release page of this repo to download a ready to use binary for mac. Otherwise you have to compile the source code yourself first.

**Comment by taylorzhancher** [comment]
It's working!! Thank you so much for the code and your additional instructions. Wish you best of luck in finances too!!
